#!/usr/bin/env ruby

require "bundler/setup"
require "snapit"
require "thor"

class SnapitCLI < Thor
  desc "hello", "hello name"
  def hello
    puts "hello mark"
  end

  desc "capture", "capture SCRIPT_PATH"
  def capture(script_path)
    root_path = Pathname.new(File.absolute_path("."))
    asset_path = Pathname.new(File.absolute_path(script_path))
    storage    = Snapit::Storage.new(root_path)
    Snapit.run!(asset_path, storage)
    say_status "DONE", "Results added to #{storage.output_path.to_s}"
  end
end

SnapitCLI.start(ARGV)